# Constants for Solar Position Calculations
DAYS_PER_YEAR        = 365
HOURS_PER_DAY        = 24
DEGREES_IN_CIRCLE    = 360
MINUTES_PER_DEGREE   = 4
MINUTES_PER_HOUR     = 60
SECONDS_PER_MINUTE   = 60
SUNRISE_ZENITH_ANGLE = 90.833
EARTH_TILT_ANGLE     = 23.5
MONTHS_PER_YEAR      = 12

# Constants for Farm Planning/Configuration
DEFAULT_START_MINUTE = 0
DEFAULT_START_SECOND = 0