FROM public.ecr.aws/lambda/python:3.11
ENV PIP_NO_CACHE_DIR=1 PIP_ONLY_BINARY=:all:
RUN python -m pip install --upgrade pip setuptools wheel \
 && pip install "numpy==1.26.4"
COPY ga_core.py ga_lambda.py ./
CMD ["ga_lambda.lambda_handler"]
